<?xml version="1.0" encoding="utf-8"?><Database Name="FLF" Class="FLDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MANDELA\SQLEXPRESS;Initial Catalog=FLF;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FLFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Account_Administrator" Member="Administrators" ThisKey="AccountId" OtherKey="AccountId" Type="Administrator" />
      <Association Name="Account_Coach" Member="Coaches" ThisKey="AccountId" OtherKey="AccountId" Type="Coach" />
      <Association Name="Account_Fighter" Member="Fighters" ThisKey="AccountId" OtherKey="AccountId" Type="Fighter" />
      <Association Name="Account_Trainer" Member="Trainers" ThisKey="AccountId" OtherKey="AccountId" Type="Trainer" />
    </Type>
  </Table>
  <Table Name="dbo.Administrator" Member="Administrators">
    <Type Name="Administrator">
      <Column Name="AdministratorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Administrator" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoachId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="Class_ClassTime" Member="ClassTimes" ThisKey="ClassId" OtherKey="ClassId" Type="ClassTime" />
      <Association Name="Coach_Class" Member="Coach" ThisKey="CoachId" OtherKey="CoachId" Type="Coach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassTime" Member="ClassTimes">
    <Type Name="ClassTime">
      <Column Name="ClassTimeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="Class_ClassTime" Member="Class" ThisKey="ClassId" OtherKey="ClassId" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Coach" Member="Coaches">
    <Type Name="Coach">
      <Column Name="CoachId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Coach_Class" Member="Classes" ThisKey="CoachId" OtherKey="CoachId" Type="Class" />
      <Association Name="Account_Coach" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fighter" Member="Fighters">
    <Type Name="Fighter">
      <Column Name="FighterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="Account_Fighter" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainer" Member="Trainers">
    <Type Name="Trainer">
      <Column Name="TrainerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Trainer" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
</Database>